# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: xiao_rp2040//zmk
    shield: le_colibri
  - board: xiao_rp2040//zmk
    shield: le_oeuf
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: le_oeuf
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: solanum_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: solanum_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: egg58bt_left
  - board: nice_nano//zmk
    shield: egg58bt_right
  - board: le_oeuf/nrf52840
